@startuml

skinparam sequenceMessageAlign center
title Basic ACK Handling

actor "(External) Trigger" as Trigger

box "Sending System"
participant "Originating\nSystem" as Sender
end box

box "Receiving System"
participant "Recipient" as Receiver
participant "Conformance\nTesting" as Conformer
participant "Processor" as Processor
end box

Trigger -> Sender : <b>trigger event
activate Sender

Sender -> Receiver: <b>Request
deactivate Sender
activate Receiver
Receiver --> Receiver: verify completeness \nof incoming message
activate Receiver
deactivate Receiver
Receiver --> Receiver: create Transport ACK
activate Receiver
Receiver --> Sender: Transport Ack
deactivate Receiver
activate Sender
Sender --> Sender: check for resubmission
deactivate Sender

Receiver --> Receiver: conformance testing
activate Receiver
Receiver --> Conformer: <b>test conformance
activate Conformer
Conformer -> Receiver: test result
deactivate Conformer
Receiver --> Sender: <b>(opt.) negative Transport/Appl Ack
deactivate Receiver
activate Sender
Sender --> Sender: check for error
deactivate Sender

Receiver --> Receiver: processing
activate Receiver
Receiver -> Processor: <b>start processing
activate Processor
Processor --> Receiver: processing results
deactivate Processor
Receiver --> Sender: <b>processing Appl Ack
deactivate Receiver
activate Sender
Sender --> Sender: check for error
deactivate Sender

@enduml