@startmindmap

+ Obligations

++ Conformance Verbs
+++_ positive
++++_ SHALL
++++_ SHOULD
++++_ MAY
+++_ negative
++++_ (MAYNOT)
++++_ SHOULDNOT
++++_ SHALLNOT

++ Activity
+++ to sender
++++ RESPOND
+++++_ ...
+++ to application
++++ PROCESS
+++++_ ...
++++ IGNORE
+++++_ ...
++++ INHERIT
+++++_ ...
+++ forwarding
++++ SEND
+++++_ ...

++ Data Expectation
+++ expected
++++_ ...
+++ unexpected
++++_ ...

@endmindmap