@startuml
skinparam sequenceMessageAlign center
title Request/Response with Ack without Gateways
participant "Order Placer" as Placer
participant "Intermediary" as Intermediary
participant "Order Filler" as Filler


Placer -> Filler: Task 
activate Placer
activate Filler
Filler --> Placer: 
deactivate Placer
Filler -[#red]> Placer: <b><font color=red> Application Response
activate Placer
Placer -[#red]-> Filler: <font color=red>Accept Ack 
deactivate Placer
deactivate Filler

@enduml
